### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mbuhot** [id/kastlex#11]
Hi this looks like a nice project, however I didn't see a License in the readme or source.
Could you please add your preferred open source license so I can tinker with this app?

Thanks

**Comment by mbuhot** [comment]
@id / @zmstone Would you consider adding a license file to the repo?

**Comment by id** [comment]
Hi @mbuhot. Please follow this one instead: https://github.com/klarna/kastlex.

Thanks for the tip, will fix today.

**Comment by zmstone** [comment]
yeah, this repo is the fork base,
but we have moved the development to klarna/kastlex.
@id what's the plan for this repo?
maybe add new repo to its readme ?

**Comment by mbuhot** [comment]
Thanks!
