### ISSUE TITLE
UnknownTopicOrPartition error from `mix phoenix.server`

### ISSUE THREAD

**Issue by sdball** [id/kastlex#6]
Hello! I'm a big fan of brod and I'm interested in trying out this REST proxy.

Unfortunately I'm getting an error when starting the endpoint. Is there some required configuration that I'm missing?

```
$ mix phoenix.server
09:28:38.609 [info]  Running Kastlex.Endpoint with Cowboy using http://localhost:8092
09:28:38.679 [info]  Connecting to {127, 0, 0, 1}:2181

09:28:38.679 [info]  Connected {127, 0, 0, 1}:2181, sending connect command

09:28:38.679 [info]  Connection to {127, 0, 0, 1}:2181 is established

09:28:38.731 [error]  GenServer #PID<0.335.0> terminating
** (MatchError) no match of right hand side value: {:error, :UnknownTopicOrPartition}
    (brod) src/brod_topic_subscriber.erl:182: :brod_topic_subscriber.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$start_consumer", [begin_offset: :earliest], [], :all}
State: {:state, :kastlex, "__consumer_offsets", [], Kastlex.CgStatusCollector, %{}, :undefined, []}
```

Kafka/zookeeper seem to be running fine. I can get data from an existing topic with `kafkacat`:

```
$ kafkacat -b localhost:9092 -t commitlog -p 0 -o beginning
```

**Comment by id** [comment]
Thanks for the report, I'll fix it later today.

Kastlex is trying to connect to __consumer_offsets topic, but this one does not exist on your node. It is created automatically by Kafka when it gets a connection from consumer using consumer groups protocol.

The simplest way to fix it is to run a script from kafka distribution: `bin/kafka-console-consumer.sh --new-consumer --bootstrap-server localhost:9092 --topic commitlog`
